### ISSUE TITLE
demo-phone  cannot dail with crosswalk?

### ISSUE THREAD

**Issue by amosli** [onsip/sipjs-examples#2]
Hi,All:
I do as follows:
http://sipjs.com/guides/mobile/android-native/

ENV: 
Android 5.1
Crosswalk: crosswalk-22.52.561.4.zip

build an android app with crosswalk, register is ok, can call others, but cannot talk; While others can call me, and I can hear others, but I'm mute to others;
so,  can someone help me?

**Comment by egreenmachine** [comment]
Please follow the guide. We do not support any mobile support outside of what the guide entails.
